In [1]:
import pandas as pd

In [4]:
# read the data with pandas
cali = pd.read_csv("Cali.csv")

# Print the first 5 rows of the data
cali.head()

,Incident_ID,Date,Location,Area_Burned (Acres),Homes_Destroyed,Businesses_Destroyed,Vehicles_Damaged,Injuries,Fatalities,Estimated_Financial_Loss (Million $),Cause
0,INC1000,2020-11-22,Sonoma County,14048,763,474,235,70,19,2270.57,Lightning
1,INC1001,2021-09-23,Sonoma County,33667,1633,4,263,100,2,1381.14,Lightning
2,INC1002,2022-02-10,Shasta County,26394,915,291,31,50,6,2421.96,Human Activity
3,INC1003,2021-05-17,Sonoma County,20004,1220,128,34,28,0,3964.16,Unknown
4,INC1004,2021-09-22,Sonoma County,40320,794,469,147,0,15,1800.09,Unknown

In [5]:
# Display the data types and null values

print(cali.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Incident_ID                           100 non-null    object
 1   Date                                  100 non-null    object
 2   Location                              100 non-null    object
 3   Area_Burned (Acres)                   100 non-null    int64
 4   Homes_Destroyed                       100 non-null    int64
 5   Businesses_Destroyed                  100 non-null    int64
 6   Vehicles_Damaged                      100 non-null    int64
 7   Injuries                              100 non-null    int64
 8   Fatalities                            100 non-null    int64
 9   Estimated_Financial_Loss (Million $)  100 non-null    float64
 10  Cause                                 100 non-null    object
dtypes: float64(1), int64(6), object(4)
memory usage: 8.7+ KB
None

In [15]:
# Check if there are duplicates and drop if found.

# Check if there are duplicates and drop if found.
duplicates = cali.duplicated().sum()  # Count duplicates

if duplicates > 0:
    print(f'Total duplicates: {duplicates}')
    cali = cali.drop_duplicates()  # Drop duplicates
else:
    print('No duplicates found')
print('No duplicates found')

No duplicates found
No duplicates found

In [22]:
# Rename the column that are too long
cali = cali.rename(columns={"Area_Burned (Acres)": "Area_Burned",
                            "Estimated_Financial_Loss (Million $)": "Estimated_Loss"})
print(cali.head())

  Incident_ID        Date       Location  Area_Burned  Homes_Destroyed  \
0     INC1000  2020-11-22  Sonoma County        14048              763
1     INC1001  2021-09-23  Sonoma County        33667             1633
2     INC1002  2022-02-10  Shasta County        26394              915
3     INC1003  2021-05-17  Sonoma County        20004             1220
4     INC1004  2021-09-22  Sonoma County        40320              794

   Businesses_Destroyed  Vehicles_Damaged  Injuries  Fatalities  \
0                   474               235        70          19
1                     4               263       100           2
2                   291                31        50           6
3                   128                34        28           0
4                   469               147         0          15

   Estimated_Loss           Cause
0         2270.57       Lightning
1         1381.14       Lightning
2         2421.96  Human Activity
3         3964.16         Unknown
4         1800.09         Unknown

In [24]:
# Describe the data
cali.describe()

,Area_Burned,Homes_Destroyed,Businesses_Destroyed,Vehicles_Damaged,Injuries,Fatalities,Estimated_Loss
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,26531.460000,941.890000,251.570000,150.330000,42.040000,9.930000,2396.099300
std,14282.123824,543.019967,138.317761,88.471197,29.201467,5.682251,1430.439422
min,357.000000,18.000000,4.000000,5.000000,0.000000,0.000000,52.590000
25%,15916.250000,501.000000,134.750000,70.750000,16.000000,5.000000,1175.195000
50%,25618.000000,908.500000,256.500000,150.500000,37.000000,10.000000,2408.530000
75%,39775.000000,1401.750000,371.000000,229.750000,60.000000,14.250000,3662.110000
max,49653.000000,1968.000000,493.000000,300.000000,100.000000,20.000000,4866.990000

In [25]:
# Get the last rows of the data.
cali.tail()

,Incident_ID,Date,Location,Area_Burned,Homes_Destroyed,Businesses_Destroyed,Vehicles_Damaged,Injuries,Fatalities,Estimated_Loss,Cause
95,INC1095,2018-01-16,Mendocino County,13112,1468,46,281,89,17,4008.58,Human Activity
96,INC1096,2022-07-07,Shasta County,39209,710,282,189,34,14,376.72,Human Activity
97,INC1097,2016-05-18,Shasta County,11863,702,9,40,100,1,1474.78,Human Activity
98,INC1098,2014-06-24,Napa Valley,1338,1619,262,293,94,3,3308.74,Human Activity
99,INC1099,2021-03-20,Mendocino County,44299,1217,172,176,81,20,4276.78,Human Activity

In [27]:
# Change date to date time
cali["Date"] = pd.to_datetime(cali["Date"])

In [28]:
# Trim whitespace
cali.columns = cali.columns.str.strip()
cali["Cause"] = cali["Cause"].str.strip()

In [29]:
# Lowercase text
cali["Cause"] = cali["Cause"].str.lower()

In [30]:
# Ensure categorical values are consistent
print(cali["Cause"].unique())  # Check unique values

['lightning' 'human activity' 'unknown']

In [32]:
cali.to_csv("califo.csv")
print("File is saved")

File is saved